# Generated by Django 5.0.2 on 2024-03-03 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Platform_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('link', models.CharField(choices=[('android link', 'Android Link'), ('ios link', 'Ios Link'), ('desktop link', 'Desktop Link')], db_index=True, default='live account', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_type_name', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='client', max_length=20)),
                ('benificary_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ifsc_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('logo', models.ImageField(null=True, upload_to='company/logo')),
                ('mobile_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('linkdin_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('whatsapp_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('telegram_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('shortname', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('code', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('EMAIL_BACKEND', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('EMAIL_USE_TLS', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('EMAIL_HOST', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('EMAIL_PORT', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('EMAIL_HOST_USER', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('EMAIL_HOST_PASSWORD', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forex_Manager_Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('login', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_type_name', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='client', max_length=20)),
                ('wallet_type_name', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='usdt', max_length=20)),
                ('wallet_address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
