# Generated by Django 5.0.2 on 2024-03-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_add_platform_link_bank_detail_company_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Group',
            new_name='Forex_Group',
        ),
    ]
