# Generated by Django 5.0.2 on 2024-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_demo_acount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo_Acount',
            new_name='Demo_Account',
        ),
    ]
