# Generated by Django 5.0.2 on 2024-03-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDocument',
            new_name='UserDocuments',
        ),
    ]
