# Generated by Django 5.0.2 on 2024-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_client_register_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
