# Generated by Django 5.0.2 on 2024-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_userdeposits_usdt_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdt',
            name='usdt',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
    ]
