# Generated by Django 5.0.2 on 2024-03-24 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_uploaddocument_delete_userdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
