# Generated by Django 5.0.2 on 2024-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_client_register_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='otp_status',
            field=models.BooleanField(default=False),
        ),
    ]
