# Generated by Django 5.0.2 on 2024-03-09 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_otp_status_remove_client_register_otp_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('login', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('leverage', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('main_password', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('invest_password', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone_password', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
