# Generated by Django 5.0.2 on 2024-03-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_otp_status_remove_client_register_otp_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_register',
            old_name='gender',
            new_name='address',
        ),
    ]
