# Generated by Django 5.0.2 on 2024-03-28 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_demoaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoAccount',
            new_name='DemoAccounts',
        ),
    ]
