# Generated by Django 5.0.2 on 2024-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_userdeposits_usdt_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeposits',
            name='action_choice',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('live', 'Live')], db_index=True, default='wallet'),
        ),
    ]
