# Generated by Django 5.0.2 on 2024-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_userdeposits_action_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdt',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
