# Generated by Django 5.0.2 on 2024-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_alter_liveaccount_user_delete_demoaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, max_length=1, null=True),
        ),
    ]
