# Generated by Django 5.0.2 on 2024-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_usdt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_account_number', models.TextField(blank=True, db_index=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ifsc_code', models.FileField(blank=True, db_index=True, null=True, upload_to='user_upload_document')),
                ('deposit_choice', models.CharField(choices=[('usdt', 'USDT'), ('bank', 'BANK')], db_index=True, default='bank')),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
