# Generated by Django 5.0.2 on 2024-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_status',
            name='status',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('deposit', 'Deposit')], db_index=True, default='bank'),
        ),
    ]
