# Generated by Django 5.0.2 on 2024-03-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_alter_client_register_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='user_wallet',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='UserDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(blank=True, db_index=True, null=True)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('transaction_ID', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('recipet', models.FileField(blank=True, db_index=True, null=True, upload_to='user_upload_document')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('action_choice', models.IntegerField(choices=[('wallet', 'Wallet'), ('live', 'Live')], db_index=True, default=0)),
                ('deposit_from', models.TextField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, db_index=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
