# Generated by Django 5.0.2 on 2024-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_internal_transfer_liveaccount_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='internal_transfer',
            name='transfer_to',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
