# Generated by Django 5.0.2 on 2024-04-02 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_internal_transfer_transfer_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internal_transfer',
            old_name='transaction_ID',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='internal_transfer',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
