# Generated by Django 5.0.2 on 2024-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0016_rename_transaction_id_internal_transfer_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeposits',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
